### ISSUE TITLE
How can I predict faster?

### ISSUE THREAD

**Issue by Cheneng** [G-Wang/WaveRNN-Pytorch#4]
I found it's slow to evaluate the result, and it's far from being a real time one, so how can I predict faster?

**Comment by G-Wang** [comment]
Hi I'm working on automating the mel batching and wav stitching (should be done in a few days), I'm not sure how close to real time it will get, but currently without optimization I'm generating around 2100 samples/second. To get to 22kHz (real time) generation speech, it's about 10 times speed up, which I think with sufficient large batching, will be doable.

**Comment by Cheneng** [comment]
Looking forward to your update and I am curious about how to do the batched sampling too.

**Comment by G-Wang** [comment]
@Cheneng Hi, there's been development on a fork of my repo that includes good batch synthesis here (https://github.com/geneing/WaveRNN-Pytorch/tree/model_simplification). I haven't tested it yet but it should work very well. Feel free to check it out, I'll update my repo with it later this month.

**Comment by Cheneng** [comment]
Thanks

**Comment by acrosson** [comment]
Hi @G-Wang ,

How can I test the batch synthesize you implemented?

You mentioned [here](https://github.com/fatchord/WaveRNN/issues/9#issuecomment-439661423) you were able to get the model to perform quite well.
