### ISSUE TITLE
why is randint? 

### ISSUE THREAD

**Issue by hdmjdp** [G-Wang/WaveRNN-Pytorch#5]
mel_offsets = [np.random.randint(0, offset) for offset in max_offsets]

why is randint?

**Comment by G-Wang** [comment]
The way Fatcord has the data loading setup, to avoid dealing with variable wav/mel length for each wav file, he use a fixed window (see `hparams.seq_len`) to train, and thus randint here is used to randomly select the starting point of the fixed segment of wav/mel to be used as part of the batch for training.
